//! SQL compilation: schema IR + filter/sort/page IR → parameterized statements.
//!
//! # The injection boundary
//!
//! Exactly three kinds of text reach the generated SQL, and each has a different
//! guarantee:
//!
//! | Text                        | Origin                          | Guarantee                        |
//! |-----------------------------|---------------------------------|----------------------------------|
//! | schema / table / column     | derived from parsed SDL         | generated by us, never client    |
//! | operators, `ASC`/`DESC`     | `match` on our own enums        | `&'static str`, not data         |
//! | **every client value**      | GraphQL arguments               | bound as `$1, $2, …`, always     |
//!
//! There is no fourth category. A client selects fields by GraphQL name; that
//! name is resolved through [`superquery_query_core::SchemaIr`] before any SQL is
//! built, and an unknown name is an error rather than a passthrough. So a field
//! called `id"; DROP TABLE --` cannot exist: it would have failed schema lookup.
//!
//! Integer limits are interpolated rather than bound. They are `u32`s this crate
//! computed and clamped — not client text — so there is nothing to escape.

use superquery_query_core::filter::CmpOp;
use superquery_query_core::pagination::PageDirection;
use superquery_query_core::schema::{Entity, FieldKind};
use superquery_query_core::{Cursor, FilterExpr, Ordering, PageRequest, ScalarType};

use crate::error::{PgError, PgResult};
use crate::pool::validate_ident;

/// The table alias every generated statement uses.
///
/// Not cosmetic. The SELECT list projects `"value"::text AS "value"`, and SQL
/// resolves `ORDER BY <name>` against output aliases *before* input columns — so
/// an unqualified `ORDER BY "value"` would sort the text rendering and put
/// `9000` above `115792…`. `WHERE` never sees output aliases, so the keyset
/// predicate would disagree with the ordering it is supposed to page through.
///
/// Qualifying every column reference as `e."col"` makes both resolve to the
/// input column, with its real type.
const T: &str = "e";

/// A statement plus its bound parameters.
///
/// Parameters are all `Option<String>`: values are bound as text and cast in SQL
/// (`$1::text::numeric`), which is how the node binds them too. It keeps 256-bit
/// numerics exact — they never pass through a float — and avoids a combinatorial
/// explosion of `ToSql` impls per scalar type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SqlQuery {
    pub sql: String,
    pub params: Vec<Option<String>>,
}

impl SqlQuery {
    /// Borrow the params in the form `tokio_postgres` wants.
    pub fn params_as_refs(&self) -> Vec<&(dyn tokio_postgres::types::ToSql + Sync)> {
        self.params
            .iter()
            .map(|p| p as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect()
    }
}

/// One column in the SELECT list, with everything needed to decode it back.
#[derive(Debug, Clone)]
pub struct ProjectedField {
    /// GraphQL field name — the key in the response object.
    pub name: String,
    /// Postgres column it came from.
    pub column: String,
    pub scalar: ScalarType,
    pub is_list: bool,
}

/// Accumulates bound parameters and hands out `$n` placeholders.
#[derive(Default)]
struct Params {
    values: Vec<Option<String>>,
}

impl Params {
    /// Bind a value, returning its placeholder. The counter is the length, so
    /// placeholders can never collide or skip.
    fn bind(&mut self, value: Option<String>) -> String {
        self.values.push(value);
        format!("${}", self.values.len())
    }
}

/// The columns to select for an entity, in a stable order.
///
/// Derived (`@derivedFrom`) fields are excluded — they have no column and are
/// resolved by a separate query against the owning side.
pub fn projection(entity: &Entity) -> Vec<ProjectedField> {
    entity
        .stored_fields()
        .filter_map(|f| {
            Some(ProjectedField {
                name: f.name.clone(),
                column: f.column.clone()?,
                scalar: f.scalar()?,
                is_list: f.is_list,
            })
        })
        .collect()
}

/// Render the SELECT list. `Bytes` becomes hex, everything else `::text`.
fn select_list(fields: &[ProjectedField]) -> String {
    fields
        .iter()
        .map(|f| {
            let quoted = format!("{T}.\"{}\"", f.column);
            // Lists live in jsonb; ::text renders them as JSON, which the
            // GraphQL layer parses back. Bytes needs encode(), not ::text.
            let expr = if f.is_list {
                format!("{quoted}::text")
            } else {
                f.scalar.select_expr(&quoted)
            };
            format!("{expr} AS \"{}\"", f.column)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Fully-qualified, quoted table reference.
fn table_ref(schema: &str, entity: &Entity) -> PgResult<String> {
    // The only operator-supplied identifier in the whole builder.
    validate_ident(schema)?;
    Ok(format!("\"{schema}\".\"{}\" AS {T}", entity.table))
}

/// `SELECT … WHERE id = $1` — the by-ID resolver (Milestone 4).
pub fn select_by_id(
    schema: &str,
    entity: &Entity,
    id: &str,
) -> PgResult<(SqlQuery, Vec<ProjectedField>)> {
    let fields = projection(entity);
    let mut params = Params::default();
    let ph = params.bind(Some(id.to_string()));
    let sql = format!(
        "SELECT {} FROM {} WHERE {T}.\"id\" = {ph} LIMIT 1",
        select_list(&fields),
        table_ref(schema, entity)?,
    );
    Ok((
        SqlQuery {
            sql,
            params: params.values,
        },
        fields,
    ))
}

/// `SELECT … WHERE id = ANY($1)` — the batched form.
///
/// This exists for relation resolution (Milestone 8): a DataLoader collects the
/// ids requested across a whole GraphQL layer and issues **one** statement,
/// instead of one per parent row. That is the difference between an N+1 storm
/// and a single index scan.
pub fn select_by_ids(
    schema: &str,
    entity: &Entity,
    ids: &[String],
) -> PgResult<(SqlQuery, Vec<ProjectedField>)> {
    let fields = projection(entity);
    // ANY() takes one array parameter, so the statement text is identical
    // regardless of how many ids are batched — good for the plan cache.
    //
    // Bound as text and cast in SQL. A bare `$1::text[]` makes the driver type
    // the parameter itself as `text[]`, and the array literal we bind is a
    // String, so every batched lookup failed with "error serializing
    // parameter 0".
    let sql = format!(
        "SELECT {} FROM {} WHERE {T}.\"id\" = ANY($1::text::text[])",
        select_list(&fields),
        table_ref(schema, entity)?,
    );
    Ok((
        SqlQuery {
            sql,
            params: vec![Some(text_array_literal(ids))],
        },
        fields,
    ))
}

/// `SELECT … WHERE fk = ANY($1)`, capped per parent — the batched reverse
/// relation.
///
/// A `@derivedFrom` field asks "every `Transfer` whose `fromAccount` is this
/// account". Resolving that once per parent is the N+1 the DataLoader exists to
/// remove, so all parent ids in a layer go into one `ANY($1)`.
///
/// The cap cannot be a plain `LIMIT`: that would bound the *whole batch*, and
/// one busy parent would starve the rest. `row_number()` partitioned by the FK
/// bounds each parent independently, ordered by `id` so the cut is
/// deterministic. The outer query re-selects the projected columns by name so
/// rows still decode positionally and `__rn` never reaches the client.
pub fn select_by_parent_ids(
    schema: &str,
    entity: &Entity,
    fk_field: &str,
    parent_ids: &[String],
    per_parent_limit: u32,
) -> PgResult<(SqlQuery, Vec<ProjectedField>)> {
    let fk = entity
        .field(fk_field)
        .filter(|f| matches!(f.kind, FieldKind::Relation { .. }))
        .and_then(|f| f.column.clone())
        .ok_or_else(|| {
            PgError::Core(superquery_query_core::CoreError::UnknownField {
                entity: entity.name.clone(),
                field: format!("{fk_field} (not a foreign key)"),
            })
        })?;

    let fields = projection(entity);
    let outer = fields
        .iter()
        .map(|f| format!("w.\"{}\"", f.column))
        .collect::<Vec<_>>()
        .join(", ");

    // Interpolated, not bound: a u32 this crate clamped. See module docs.
    let sql = format!(
        "SELECT {outer} FROM (\
           SELECT {}, row_number() OVER (PARTITION BY {T}.\"{fk}\" ORDER BY {T}.\"id\" ASC) AS \"__rn\" \
           FROM {} WHERE {T}.\"{fk}\" = ANY($1::text::text[])\
         ) AS w WHERE w.\"__rn\" <= {per_parent_limit} ORDER BY w.\"{fk}\", w.\"id\"",
        select_list(&fields),
        table_ref(schema, entity)?,
    );

    Ok((
        SqlQuery {
            sql,
            params: vec![Some(text_array_literal(parent_ids))],
        },
        fields,
    ))
}

/// Render ids as a Postgres array literal, cast back by `::text::text[]`.
///
/// Still one bound parameter: the literal is data, so quoting here only has to
/// satisfy the array parser, not the SQL parser.
fn text_array_literal(ids: &[String]) -> String {
    format!(
        "{{{}}}",
        ids.iter()
            .map(|i| format!("\"{}\"", i.replace('\\', "\\\\").replace('"', "\\\"")))
            .collect::<Vec<_>>()
            .join(",")
    )
}

/// The collection query: filter + order + keyset page (Milestones 5–7).
pub fn select_collection(
    schema: &str,
    entity: &Entity,
    filter: Option<&FilterExpr>,
    ordering: &Ordering,
    page: &PageRequest,
) -> PgResult<(SqlQuery, Vec<ProjectedField>)> {
    let fields = projection(entity);
    let mut params = Params::default();
    let mut predicates = Vec::new();

    if let Some(f) = filter {
        predicates.push(compile_filter(entity, f, &mut params)?);
    }

    // Backward pagination walks the ordering in reverse, then the caller
    // un-reverses the rows. That way one code path serves both directions.
    let effective_ordering = match page.direction {
        PageDirection::Forward => ordering.clone(),
        PageDirection::Backward => ordering.reversed(),
    };

    if let Some(cursor) = &page.cursor {
        predicates.push(keyset_predicate(
            entity,
            &effective_ordering,
            cursor,
            &mut params,
        )?);
    }

    let where_clause = if predicates.is_empty() {
        String::new()
    } else {
        format!(" WHERE {}", predicates.join(" AND "))
    };

    // Interpolated, not bound: a u32 this crate clamped. See module docs.
    let sql = format!(
        "SELECT {} FROM {}{} ORDER BY {} LIMIT {}",
        select_list(&fields),
        table_ref(schema, entity)?,
        where_clause,
        effective_ordering.to_sql_with_alias(Some(T)),
        page.fetch_limit(),
    );

    Ok((
        SqlQuery {
            sql,
            params: params.values,
        },
        fields,
    ))
}

/// Compile a filter tree into a SQL predicate.
fn compile_filter(entity: &Entity, expr: &FilterExpr, params: &mut Params) -> PgResult<String> {
    Ok(match expr {
        FilterExpr::Compare { field, op, value } => {
            let (scalar, is_list) = resolve_scalar(entity, field.name())?;
            let ph = params.bind(scalar.encode_param(value)?);
            format!(
                "{T}.\"{}\" {} {}",
                field.column(),
                op.sql(),
                scalar.param_cast(&ph, is_list)
            )
        }
        FilterExpr::In { field, values } => {
            let (scalar, is_list) = resolve_scalar(entity, field.name())?;
            if values.is_empty() {
                // `IN ()` is a syntax error; an empty set matches nothing.
                return Ok("FALSE".to_string());
            }
            let placeholders = values
                .iter()
                .map(|v| {
                    let ph = params.bind(scalar.encode_param(v)?);
                    Ok(scalar.param_cast(&ph, is_list))
                })
                .collect::<PgResult<Vec<_>>>()?;
            format!(
                "{T}.\"{}\" IN ({})",
                field.column(),
                placeholders.join(", ")
            )
        }
        FilterExpr::IsNull { field, negated } => {
            let op = if *negated { "IS NOT NULL" } else { "IS NULL" };
            format!("{T}.\"{}\" {op}", field.column())
        }
        FilterExpr::Not(inner) => format!("NOT ({})", compile_filter(entity, inner, params)?),
        FilterExpr::And(parts) | FilterExpr::Or(parts) => {
            if parts.is_empty() {
                // An empty AND is vacuously true; an empty OR matches nothing.
                return Ok(match expr {
                    FilterExpr::And(_) => "TRUE".to_string(),
                    _ => "FALSE".to_string(),
                });
            }
            let joiner = if matches!(expr, FilterExpr::And(_)) {
                " AND "
            } else {
                " OR "
            };
            let compiled = parts
                .iter()
                .map(|p| compile_filter(entity, p, params))
                .collect::<PgResult<Vec<_>>>()?;
            format!("({})", compiled.join(joiner))
        }
    })
}

/// The keyset ("seek") predicate that replaces OFFSET.
///
/// For an ordering `(a ASC, b DESC, id ASC)` and a cursor `(a₀, b₀, id₀)`, the
/// rows strictly after the cursor are:
///
/// ```text
///   (a > a₀)
///   OR (a = a₀ AND b < b₀)
///   OR (a = a₀ AND b = b₀ AND id > id₀)
/// ```
///
/// Note the comparison flips with each key's own direction. The row-value form
/// `(a,b,id) > (a₀,b₀,id₀)` would be shorter but is only correct when every key
/// sorts the same way, which mixed `orderBy` breaks.
fn keyset_predicate(
    entity: &Entity,
    ordering: &Ordering,
    cursor: &Cursor,
    params: &mut Params,
) -> PgResult<String> {
    use superquery_query_core::sort::SortDirection;

    let keys = ordering.keys();
    debug_assert_eq!(
        keys.len(),
        cursor.values.len(),
        "arity checked in Cursor::decode"
    );

    let mut branches = Vec::with_capacity(keys.len());

    for i in 0..keys.len() {
        let mut conjuncts = Vec::with_capacity(i + 1);

        // Equality on every earlier key…
        for (key, value) in keys.iter().zip(&cursor.values).take(i) {
            let (scalar, is_list) = resolve_scalar(entity, key.field.name())?;
            let v = require_non_null(value, key.field.name())?;
            let ph = params.bind(Some(v.clone()));
            conjuncts.push(format!(
                "{T}.\"{}\" = {}",
                key.field.column(),
                scalar.param_cast(&ph, is_list)
            ));
        }

        // …then a strict comparison on this one, in its own direction.
        let key = &keys[i];
        let (scalar, is_list) = resolve_scalar(entity, key.field.name())?;
        let v = require_non_null(&cursor.values[i], key.field.name())?;
        let ph = params.bind(Some(v.clone()));
        let op = match key.direction {
            SortDirection::Asc => CmpOp::Gt,
            SortDirection::Desc => CmpOp::Lt,
        };
        conjuncts.push(format!(
            "{T}.\"{}\" {} {}",
            key.field.column(),
            op.sql(),
            scalar.param_cast(&ph, is_list)
        ));

        branches.push(format!("({})", conjuncts.join(" AND ")));
    }

    Ok(format!("({})", branches.join(" OR ")))
}

/// Ordering keys must be non-NULL for the keyset comparison to be total.
///
/// The GraphQL layer only generates `orderBy` values for non-nullable orderable
/// fields, so this should be unreachable in practice — but a hand-crafted cursor
/// could carry a null, and silently returning wrong rows is worse than an error.
fn require_non_null<'a>(value: &'a Option<String>, field: &str) -> PgResult<&'a String> {
    value.as_ref().ok_or_else(|| {
        PgError::Core(superquery_query_core::CoreError::InvalidCursor(format!(
            "cursor contains a null value for ordering key `{field}`"
        )))
    })
}

/// Look up a field's scalar type, rejecting names not on the entity.
///
/// This is the lookup that makes the injection guarantee hold: a `Field` in the
/// IR carries a column name we generated, and this re-checks it against the
/// entity before its type is used to build a cast.
fn resolve_scalar(entity: &Entity, field_name: &str) -> PgResult<(ScalarType, bool)> {
    let field = entity.field(field_name).ok_or_else(|| {
        PgError::Core(superquery_query_core::CoreError::UnknownField {
            entity: entity.name.clone(),
            field: field_name.to_string(),
        })
    })?;
    if matches!(field.kind, FieldKind::Derived { .. }) {
        return Err(PgError::Core(
            superquery_query_core::CoreError::UnknownField {
                entity: entity.name.clone(),
                field: format!("{field_name} (derived fields have no column to compare)"),
            },
        ));
    }
    let scalar = field.scalar().ok_or_else(|| {
        PgError::Core(superquery_query_core::CoreError::UnknownField {
            entity: entity.name.clone(),
            field: field_name.to_string(),
        })
    })?;
    Ok((scalar, field.is_list))
}

#[cfg(test)]
mod tests {
    use super::*;
    use superquery_query_core::filter::Field as FilterField;
    use superquery_query_core::pagination::{DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE};
    use superquery_query_core::sort::{SortDirection, SortKey};
    use superquery_query_core::{parse_sdl, SchemaIr};

    const SDL: &str = r#"
        type Transfer @entity {
          id: ID!
          from: String!
          value: BigInt!
          blockNumber: Int!
          data: Bytes
          tags: [String!]
        }
    "#;

    fn ir() -> SchemaIr {
        parse_sdl(SDL).unwrap()
    }

    fn f(name: &str, col: &str) -> FilterField {
        FilterField::resolved(name, col)
    }

    fn page(first: Option<u32>, cursor: Option<&str>, len: usize) -> PageRequest {
        PageRequest::resolve(
            first,
            None,
            cursor,
            None,
            len,
            MAX_PAGE_SIZE,
            DEFAULT_PAGE_SIZE,
        )
        .unwrap()
    }

    #[test]
    fn by_id_is_parameterized() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let (q, _) = select_by_id("app", e, "abc").unwrap();
        assert!(q.sql.contains(r#"FROM "app"."transfers" AS e"#));
        assert!(q.sql.contains(r#"WHERE e."id" = $1"#));
        assert_eq!(q.params, vec![Some("abc".to_string())]);
    }

    #[test]
    fn injection_attempt_stays_a_parameter() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let evil = "'; DROP TABLE transfers; --";
        let (q, _) = select_by_id("app", e, evil).unwrap();
        // The payload must appear ONLY in params, never in the statement text.
        assert!(!q.sql.contains("DROP"));
        assert_eq!(q.params, vec![Some(evil.to_string())]);
    }

    #[test]
    fn bytes_projects_as_hex_and_bigint_as_text() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let (q, _) = select_by_id("app", e, "x").unwrap();
        assert!(q.sql.contains(r#"encode(e."data", 'hex') AS "data""#));
        // BigInt must never be read back through a float.
        assert!(q.sql.contains(r#"e."value"::text AS "value""#));
    }

    #[test]
    fn derived_fields_are_not_projected() {
        let sdl = r#"
            type Account @entity { id: ID! xs: [Transfer!]! @derivedFrom(field: "acct") }
            type Transfer @entity { id: ID! acct: Account! }
        "#;
        let ir = parse_sdl(sdl).unwrap();
        let (q, fields) = select_by_id("app", ir.entity("Account").unwrap(), "1").unwrap();
        assert!(!q.sql.contains("\"xs\""));
        assert_eq!(
            fields.iter().map(|f| f.name.as_str()).collect::<Vec<_>>(),
            ["id"]
        );
    }

    #[test]
    fn filter_compiles_to_casts_and_params() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let filter = FilterExpr::Compare {
            field: f("value", "value"),
            op: CmpOp::Gte,
            value: serde_json::json!("1000000000000000000000"),
        };
        let ordering = Ordering::default_for(f("id", "id"));
        let (q, _) =
            select_collection("app", e, Some(&filter), &ordering, &page(Some(10), None, 1))
                .unwrap();

        assert!(q.sql.contains(r#"WHERE e."value" >= $1::text::numeric"#));
        // A 21-digit value survives intact because it never becomes a number.
        assert_eq!(q.params, vec![Some("1000000000000000000000".to_string())]);
    }

    #[test]
    fn nested_and_or_nest_correctly() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let filter = FilterExpr::And(vec![
            FilterExpr::Compare {
                field: f("from", "from"),
                op: CmpOp::Eq,
                value: serde_json::json!("0xa"),
            },
            FilterExpr::Or(vec![
                FilterExpr::Compare {
                    field: f("blockNumber", "block_number"),
                    op: CmpOp::Lt,
                    value: serde_json::json!(100),
                },
                FilterExpr::IsNull {
                    field: f("data", "data"),
                    negated: false,
                },
            ]),
        ]);
        let ordering = Ordering::default_for(f("id", "id"));
        let (q, _) =
            select_collection("app", e, Some(&filter), &ordering, &page(Some(5), None, 1)).unwrap();

        assert!(q.sql.contains(
            r#"(e."from" = $1 AND (e."block_number" < $2::text::integer OR e."data" IS NULL))"#
        ));
        assert_eq!(q.params.len(), 2);
    }

    #[test]
    fn empty_in_list_matches_nothing_instead_of_erroring() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let filter = FilterExpr::In {
            field: f("from", "from"),
            values: vec![],
        };
        let ordering = Ordering::default_for(f("id", "id"));
        let (q, _) =
            select_collection("app", e, Some(&filter), &ordering, &page(Some(5), None, 1)).unwrap();
        assert!(q.sql.contains("WHERE FALSE"));
    }

    #[test]
    fn unknown_filter_field_is_rejected() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let filter = FilterExpr::Compare {
            field: f("nonexistent", "nonexistent"),
            op: CmpOp::Eq,
            value: serde_json::json!("x"),
        };
        let ordering = Ordering::default_for(f("id", "id"));
        assert!(
            select_collection("app", e, Some(&filter), &ordering, &page(Some(5), None, 1)).is_err()
        );
    }

    #[test]
    fn collection_orders_deterministically_and_overfetches_by_one() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let ordering = Ordering::new(
            vec![SortKey::new(
                f("blockNumber", "block_number"),
                SortDirection::Desc,
            )],
            f("id", "id"),
        );
        let (q, _) =
            select_collection("app", e, None, &ordering, &page(Some(10), None, 2)).unwrap();
        // Tiebreaker present, so pages cannot overlap.
        assert!(q
            .sql
            .contains(r#"ORDER BY e."block_number" DESC, e."id" DESC"#));
        // 11 = 10 requested + 1 to detect hasNextPage.
        assert!(q.sql.ends_with("LIMIT 11"));
    }

    #[test]
    fn keyset_predicate_is_lexicographic_and_direction_aware() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let ordering = Ordering::new(
            vec![SortKey::new(
                f("blockNumber", "block_number"),
                SortDirection::Desc,
            )],
            f("id", "id"),
        );
        let cursor = Cursor::new(vec![Some("500".into()), Some("abc".into())]).encode();
        let (q, _) =
            select_collection("app", e, None, &ordering, &page(Some(10), Some(&cursor), 2))
                .unwrap();

        // DESC keys seek with `<`, and the tiebreaker follows the same direction.
        assert!(
            q.sql.contains(
                r#"((e."block_number" < $1::text::integer) OR (e."block_number" = $2::text::integer AND e."id" < $3))"#
            ),
            "got: {}", q.sql
        );
    }

    #[test]
    fn backward_pagination_reverses_the_ordering() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let ordering = Ordering::default_for(f("id", "id"));
        let p = PageRequest::resolve(
            None,
            Some(5),
            None,
            None,
            1,
            MAX_PAGE_SIZE,
            DEFAULT_PAGE_SIZE,
        )
        .unwrap();
        let (q, _) = select_collection("app", e, None, &ordering, &p).unwrap();
        assert!(q.sql.contains(r#"ORDER BY e."id" DESC"#));
    }

    #[test]
    fn batched_select_uses_one_array_param() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let (q, _) = select_by_ids("app", e, &["a".into(), "b".into()]).unwrap();
        assert!(q.sql.contains(r#"e."id" = ANY($1::text::text[])"#));
        assert_eq!(q.params, vec![Some("{\"a\",\"b\"}".to_string())]);
    }

    #[test]
    fn ordering_is_qualified_so_it_cannot_bind_to_a_text_alias() {
        // Regression. The SELECT list projects `e."value"::text AS "value"`, and
        // SQL resolves ORDER BY against output aliases *before* input columns.
        // Unqualified, `ORDER BY "value"` therefore sorted the text rendering —
        // 9000 above 115792…, and `1` last.
        //
        // It also broke pagination: the keyset predicate lives in WHERE, which
        // never sees output aliases, so the ordering and the seek disagreed.
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        let ordering = Ordering::new(
            vec![SortKey::new(f("value", "value"), SortDirection::Desc)],
            f("id", "id"),
        );
        let (q, _) = select_collection("app", e, None, &ordering, &page(Some(5), None, 2)).unwrap();

        assert!(
            q.sql.contains(r#"ORDER BY e."value" DESC"#),
            "ORDER BY must be table-qualified, got: {}",
            q.sql
        );
        assert!(
            !q.sql.contains(r#"ORDER BY "value""#),
            "unqualified ORDER BY sorts numerics lexicographically: {}",
            q.sql
        );
    }

    #[test]
    fn bad_schema_name_is_rejected_before_sql() {
        let ir = ir();
        let e = ir.entity("Transfer").unwrap();
        assert!(select_by_id("app\"; DROP SCHEMA public; --", e, "x").is_err());
    }
}
